from typing import List, Tuple
from brainfuck.base import BrainfuckBackend
from middleend.brainfuck_ast import CommandNode, LoopNode, ProgramNode

class OpCode:
    INC = 0x01      # +
    DEC = 0x02      # -
    RIGHT = 0x03    # >
    LEFT = 0x04     # <
    OUT = 0x05      # .
    INP = 0x06      # ,
    JMP_FWD = 0x10  # [ (прыжок вперёд, если 0)
    JMP_BCK = 0x11  # ] (прыжок назад)
    HALT = 0xFF     # Конец программы


class VMCompiler(BrainfuckBackend):
    """Компилятор Brainfuck в байт-код виртуальной машины"""
    
    def __init__(self):
        self.bytecode: List[int] = []
        self.jump_stack: List[int] = []  # Для обработки циклов

    def execute(self, ast: ProgramNode, output_file: str | None = None, verbose: bool = True):
        target = output_file or "program.vmbf"
        return self.compile(ast, output_file=target, verbose=verbose)

    def compile(self, ast: ProgramNode, output_file: str = "program.vmbf", verbose: bool = True) -> str:
        self.bytecode = []
        self.jump_stack = []

        self._compile_node(ast)
        self.bytecode.append(OpCode.HALT)

        #сохранение в бинарник
        with open(output_file, "wb") as f:
            f.write(bytes(self.bytecode))

        if verbose:
            print(f"Generated bytecode: {output_file}")
            print(f"Size: {len(self.bytecode)} bytes")
            self._print_bytecode(verbose=True)

        return output_file

    def _compile_node(self, node):
        if isinstance(node, ProgramNode):
            for child in node.body:
                self._compile_node(child)

        elif isinstance(node, LoopNode):
            jump_pos = len(self.bytecode)
            self.bytecode.append(OpCode.JMP_FWD)
            self.bytecode.append(0)  # Заглушка low
            self.bytecode.append(0)  # Заглушка high
            
            for child in node.body:
                self._compile_node(child)
            
            self.bytecode.append(OpCode.JMP_BCK)
            self.bytecode.append(jump_pos & 0xFF)
            self.bytecode.append((jump_pos >> 8) & 0xFF)
            
            loop_end = len(self.bytecode)
            self.bytecode[jump_pos + 1] = loop_end & 0xFF
            self.bytecode[jump_pos + 2] = (loop_end >> 8) & 0xFF

        elif isinstance(node, CommandNode):
            cmd = node.command
            self._compile_command(cmd)

    def _compile_command(self, cmd: str):
        if cmd == "+":
            self.bytecode.append(OpCode.INC)
        elif cmd == "-":
            self.bytecode.append(OpCode.DEC)
        elif cmd == ">":
            self.bytecode.append(OpCode.RIGHT)
        elif cmd == "<":
            self.bytecode.append(OpCode.LEFT)
        elif cmd == ".":
            self.bytecode.append(OpCode.OUT)
        elif cmd == ",":
            self.bytecode.append(OpCode.INP)
        
        elif cmd.startswith("optimized:add:"):
            val = int(cmd.split(":")[2])
            for _ in range(val):
                self.bytecode.append(OpCode.INC)
        elif cmd.startswith("optimized:sub:"):
            val = int(cmd.split(":")[2])
            for _ in range(val):
                self.bytecode.append(OpCode.DEC)
        elif cmd.startswith("optimized:right:"):
            val = int(cmd.split(":")[2])
            for _ in range(val):
                self.bytecode.append(OpCode.RIGHT)
        elif cmd.startswith("optimized:left:"):
            val = int(cmd.split(":")[2])
            for _ in range(val):
                self.bytecode.append(OpCode.LEFT)
        elif cmd == "optimized:clear":
            self.bytecode.append(OpCode.DEC) 

    def _print_bytecode(self, verbose: bool = False):
        if not verbose:
            return

        print("\nBytecode disassembly:")
        print("-" * 50)
        op_names = {
            OpCode.INC: "INC", OpCode.DEC: "DEC",
            OpCode.RIGHT: "RIGHT", OpCode.LEFT: "LEFT",
            OpCode.OUT: "OUT", OpCode.INP: "INP",
            OpCode.JMP_FWD: "JMP_FWD", OpCode.JMP_BCK: "JMP_BCK",
            OpCode.HALT: "HALT",
        }

        i = 0
        while i < len(self.bytecode):
            op = self.bytecode[i]
            name = op_names.get(op, f"UNKNOWN({op})")

            if op in [OpCode.JMP_FWD, OpCode.JMP_BCK]:
                addr = self.bytecode[i + 1] | (self.bytecode[i + 2] << 8)
                print(f"  {i:04d}: {name:10s} -> {addr}")
                i += 3
            else:
                print(f"  {i:04d}: {name}")
                i += 1

        print("-" * 50)


__all__ = ["VMCompiler", "OpCode"]